In [3]:
import numpy as np
print("Numpy Version ",np.version)
arr = np.array([8, 4, 6, 8, 2])
print(arr)

Numpy Version  <module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>
[8 4 6 8 2]


In [4]:
print("Type of array", type(arr))
print("Dimension of array arr is", arr.ndim)
de= np.array(23)
print("Dimension of array de is", de.ndim)
fruit_list=["Apple", "Mango", "Banana"]
print(fruit_list)
print("Type of fruit list is ", type(fruit_list))
fruit_list = np.array(fruit_list)
print("Type of fruit list is ", type(fruit_list))

Type of array <class 'numpy.ndarray'>
Dimension of array arr is 1
Dimension of array de is 0
['Apple', 'Mango', 'Banana']
Type of fruit list is  <class 'list'>
Type of fruit list is  <class 'numpy.ndarray'>


In [5]:
import numpy as np
A = np.array([8, 4, 6, 8, 2])
print(A)
B= np.array([[1, 2, 3], [4, 5, 6]])
print(B)
C = np.array([[ [1, 2, 3], [4, 5, 6], [14, 15, 16]]])
print(C)
C_dimensions = C.ndim
print (C_dimensions)

[8 4 6 8 2]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [14 15 16]]]
3


In [8]:
d1 = np.array ([6,8,1,2])
print("The dimension of array di is ",d1.ndim)
print("Elements of array di are ",d1)
d2 = np.array([[58,69,34,45], [25,65,68,99], [56,98,1,2]])
print("Elements of array d2 are ",d2)
print("The dimension of array d2 is ",d2.ndim)
print("Element at (1,8) row 1 column e is ",d2[1,0])

The dimension of array di is  1
Elements of array di are  [6 8 1 2]
Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
The dimension of array d2 is  2
Element at (1,8) row 1 column e is  25


In [12]:
import numpy as np
d3array = np.array ([
[
  [1, 2, 3],
  [4, 5, 6],
],
[
  [7, 8, 9],
  [10, 11, 12],
],
[
  [13, 14, 15],
  [16, 17, 18],
]
])
print("The dimension of array d3array is ",d3array.ndim)
print(d3array)
item = d3array [2] [0] [0]
print("Item at daarray[2] [0] [0] is: ",d3array[2] [0] [0])

The dimension of array d3array is  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
Item at daarray[2] [0] [0] is:  13


In [14]:
#Numpy array slicing
d1 = np.array([6,8,1,2,54,5,3]) #1-D Array
print("Elements of array di are ",d1)
print("Elements slicing 'd1 [1:5]' ",d1 [1:5])
print("Elements slicing 'd1[:3]' ",d1[:3]) #Slice elements form start index[e] to index [3], index [3] exluded
print("Elements slicing 'd1[3:]' ",d1[3:]) #Slice elements form index[3] to last index, last index exluded
print("Elements slicing 'd1[-3:-1]' ",d1[-3:-1]) #Slice elements (negative slicing) form index[-3] to index[-1], index[-1] exluded
d2 = np.array([[5,9,3,4], [21,65,8,99], [56,98,1,2]]) #2-D Array
print("Elements of array d2 are ",d2)
print("Elements slicing 'd2[0,1:3]' ",d2[0,1:3])

Elements of array di are  [ 6  8  1  2 54  5  3]
Elements slicing 'd1 [1:5]'  [ 8  1  2 54]
Elements slicing 'd1[:3]'  [6 8 1]
Elements slicing 'd1[3:]'  [ 2 54  5  3]
Elements slicing 'd1[-3:-1]'  [54  5]
Elements of array d2 are  [[ 5  9  3  4]
 [21 65  8 99]
 [56 98  1  2]]
Elements slicing 'd2[0,1:3]'  [9 3]


In [15]:
print("Array d1 slicing with step:d1[1:6:2] ",d1[1:6:2])

Array d1 slicing with step:d1[1:6:2]  [8 2 5]


In [16]:
a2 = np.array([[11, 22, 33,44], [14, 15, 16,17]]) # Create a NumPy 2D-array
a2shape = a2.shape # Get the shape of the array
a2shape = print("Shape of the array:", a2shape)

Shape of the array: (2, 4)


In [17]:
a2D = np.array([[1,2],[3,4]])
print("Array a2D",a2D)
a2D.reshape(-1)

Array a2D [[1 2]
 [3 4]]


array([1, 2, 3, 4])

In [18]:
a = np.array([1, 2, 3, 4, 5, 6])
print("Array a", a)
b = a[:2]
print("Array b",b)
b += 1
print("Array b after increment if a",b)
print('Array a', a, '; array b=', b)
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

Array a [1 2 3 4 5 6]
Array b [1 2]
Array b after increment if a [2 3]
Array a [2 3 3 4 5 6] ; array b= [2 3]
a =  [1 2 3 4] b =  [2 3]


In [19]:
d1 = np.array([6,8,1,2,54,5,3])
for x in d1:
  print(x)

6
8
1
2
54
5
3


#**Iterating 2-D Arrays**

In [21]:
d2= np.array([[58,69,34,45], [25,65,68,99], [56,98,1,2]]) #2-0 Array
print("Elements of array d2 are ",d2)
for x in d2:
  for i in x:
    print(i)

Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


In [22]:
d3 = np.array(np.array([
    [[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]],
    [[13, 14, 15],[16, 17, 18]]]))

print("The dimension of array d3 is ", d3.ndim)
print(d3)
for x in d3:
    for y in x:
        for z in y:
            print(z)


The dimension of array d3 is  3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [23]:
d2 = np.array([[58,69,34,45],[25,65,68,99],[56,98,1,2]])  #2-D Array
print("Elements of array d2 are ", d2)
for x in np.nditer(d2):
    print(x)


Elements of array d2 are  [[58 69 34 45]
 [25 65 68 99]
 [56 98  1  2]]
58
69
34
45
25
65
68
99
56
98
1
2


In [24]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
print("Array 1: ",arr1)

arr2 = np.array([7,8,9,10,11,12])
print("Array 2: ",arr2)

arr3 = np.concatenate((arr1,arr2))
print ("Concatenated array: arr3",arr3)

Array 1:  [1 2 3 4 5 6]
Array 2:  [ 7  8  9 10 11 12]
Concatenated array: arr3 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
import numpy as np

arr1 = np.array([1,2,3])
print("Array 1: ",arr1)

arr2 = np.array([7,8,9])
print("Array 2: ",arr2)

arr3 = np.stack((arr1,arr2), axis=1)
print ("Concatenated array through stack: arr3",arr3)

Array 1:  [1 2 3]
Array 2:  [7 8 9]
Concatenated array through stack: arr3 [[1 7]
 [2 8]
 [3 9]]


In [26]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
splitarr = np.array_split(arr1,3)
print("Array 1 split into 3 arrays",splitarr)
print("Array 1",splitarr[0])
print("Array 2",splitarr[1])
print("Array 3",splitarr[2])

Array 1 split into 3 arrays [array([1, 2]), array([3, 4]), array([5, 6])]
Array 1 [1 2]
Array 2 [3 4]
Array 3 [5 6]


In [27]:
import numpy as np

arr1 = np.array([1,2,3,4,5,6])
x = np.where(arr1 == 4)
print("Search index of 4",x)

Search index of 4 (array([3]),)


In [28]:
import numpy as np

arr2 = np.array([3,4,5,6,7,8])
x = np.searchsorted(arr2 , 6)
print("Index of 6 is",x)

Index of 6 is 3


In [29]:
arr2 = np.array([3, 4, 5, 6, 7, 8])
x = np.searchsorted(arr2, 6)
print("Index of 6 is", x)

# Sorting alphabetical arrays
alparr = np.array(["Cherry", "Sugar", "Floor", "Cooking Oil"])
print(alparr)
print("Sorted array", np.sort(alparr))

Index of 6 is 3
['Cherry' 'Sugar' 'Floor' 'Cooking Oil']
Sorted array ['Cherry' 'Cooking Oil' 'Floor' 'Sugar']


In [30]:
arr = np.array([[58, 69, 34, 45], [25, 65, 68, 99], [56, 98, 1, 2]])
mask = arr > 45
new_array = arr[mask]
print(new_array)  # Output: [58 69 65 68 99 56 98]

[58 69 65 68 99 56 98]


#**Last Task**

In [32]:

import numpy as np

def main():
    arr = np.arange(2, 11).reshape(3, 3).astype(float)

    flat = arr.flatten()
    max_val = flat.max()
    min_val = flat.min()

    print("3x3 array (float):")
    print(arr)
    print("\nFlattened array:")
    print(flat)
    print(f"\nMaximum value: {max_val}")
    print(f"Minimum value: {min_val}")

if __name__ == "__main__":
    main()

3x3 array (float):
[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]

Flattened array:
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]

Maximum value: 10.0
Minimum value: 2.0
